In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.externals import joblib
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb
import gc
from xgboost import XGBClassifier

%matplotlib inline

In [2]:
plt.rc('figure',dpi=100);

In [3]:
avisos = pd.read_csv("../../Data/fiuba_entrenamiento/gian/avisosONEHOT.csv")
postulaciones = pd.read_csv("../../Data/fiuba_entrenamiento/gian/postulaciones.csv")
postulantes = pd.read_csv("../../Data/fiuba_entrenamiento/gian/postulantesONEHOT.csv")

avisos['nombre_area']=avisos['nombre_area'].astype('category')

avisos_no_one_hot= pd.read_csv("../../Data/fiuba_entrenamiento/gian/avisos.csv")
avisos_no_one_hot=avisos_no_one_hot[['idaviso','tipo_de_trabajo','nivel_laboral','nombre_area']];
avisos_no_one_hot['tipo_de_trabajo']=avisos_no_one_hot['tipo_de_trabajo'].astype('category')
avisos_no_one_hot['nivel_laboral']=avisos_no_one_hot['nivel_laboral'].astype('category')
avisos_no_one_hot['nombre_area']=avisos_no_one_hot['nombre_area'].astype('category')
avisos_no_one_hot=avisos_no_one_hot.rename(columns={'nombre_area': 'nombre_area_aux'})

postulaciones['sepostulo']=1
postulaciones.drop(['fechapostulacion','dia','mes','semana','diadelasemana','hora'],axis=1,inplace=True)

In [4]:
vistas = pd.read_csv("../../Data/fiuba_entrenamiento/gian/vistas.csv")
vistas.drop(['timestamp','dia','mes','semana','diadelasemana','hora'],axis=1,inplace=True)
vistas=vistas.rename(columns={'idAviso': 'idaviso'})
vistas.head()

      idaviso idpostulante
0  1111780242      YjVJQ6Z
1  1112263876      BmVpYoR
2  1112327963      wVkBzZd
3  1112318643      OqmP9pv
4  1111903673      DrpbXDP

In [5]:
vistas_por_area=vistas.copy()
vistas_por_area['vistas_por_area']=0;
vistas_por_area=pd.merge(vistas_por_area,avisos_no_one_hot,on='idaviso', how='left')
vistas_por_area=vistas_por_area.groupby(['idpostulante','nombre_area_aux'],as_index=False).agg({'vistas_por_area':'count'})
vistas_por_area.head()

  idpostulante        nombre_area_aux  vistas_por_area
0        0005E  Tecnologia / Sistemas                2
1        00Lkv      Comercio Exterior                2
2        00dMd      Comercio Exterior                4
3        01QAq           Contabilidad                1
4        021OM      Comercio Exterior                5

In [6]:
vistas_por_nivel=vistas.copy()
vistas_por_nivel['vistas_por_nivel']=0;
vistas_por_nivel=pd.merge(vistas_por_nivel,avisos_no_one_hot,on='idaviso', how='left')
vistas_por_nivel=vistas_por_nivel.groupby(['idpostulante','nivel_laboral'],as_index=False).agg({'vistas_por_nivel':'count'})
vistas_por_nivel.head()

  idpostulante nivel_laboral  vistas_por_nivel
0        0005E          Otro                 2
1        00Lkv          Otro                 2
2        00dMd          Otro                 4
3        01QAq          Otro                 1
4        021OM          Otro                 5

In [7]:
vistas_por_tipo=vistas.copy()
vistas_por_tipo['vistas_por_tipo']=0;
vistas_por_tipo=pd.merge(vistas_por_tipo,avisos_no_one_hot,on='idaviso', how='left')
vistas_por_tipo=vistas_por_tipo.groupby(['idpostulante','tipo_de_trabajo'],as_index=False).agg({'vistas_por_tipo':'count'})
vistas_por_tipo.head()

  idpostulante tipo_de_trabajo  vistas_por_tipo
0        0005E       Full-time                2
1        00Lkv       Full-time                2
2        00dMd       Full-time                4
3        01QAq       Full-time                1
4        021OM       Full-time                5

In [8]:
vistas['cantidad']=0
vistas2=vistas.groupby(['idaviso','idpostulante'],as_index=False).agg({'cantidad':'count'})
vistas2.head()

   idaviso idpostulante  cantidad
0       18        BolNL         2
1    48375       RwVdKR         1
2   169730        1KjXB         2
3   169730       2AKzxa         2
4   169730        6LJ64         1

In [9]:
vistas=vistas.groupby(['idpostulante'],as_index=False).agg({'cantidad':'count'});
vistas.head()

  idpostulante  cantidad
0        0002q        15
1        0005E        58
2        000R8        14
3        001XE        26
4        003k9        32

In [10]:
vistas3=pd.merge(vistas2,vistas,on='idpostulante',how='left')

In [11]:
vistas3.head()

   idaviso idpostulante  cantidad_x  cantidad_y
0       18        BolNL           2          28
1    48375       RwVdKR           1          15
2   169730        1KjXB           2          99
3   169730       2AKzxa           2           2
4   169730        6LJ64           1          23

In [12]:
vistas3['cantidad']=vistas3['cantidad_x']/vistas3['cantidad_y']
vistas3.drop(['cantidad_x','cantidad_y'],axis=1,inplace=True)
vistas3.head()

   idaviso idpostulante  cantidad
0       18        BolNL  0.071429
1    48375       RwVdKR  0.066667
2   169730        1KjXB  0.020202
3   169730       2AKzxa  1.000000
4   169730        6LJ64  0.043478

In [13]:
vistas=vistas.rename(columns={'cantidad': 'vistas_postulante'})
vistas2=vistas2.rename(columns={'cantidad': 'vistas_al_aviso'})

In [14]:
postulaciones2= pd.read_csv("../../Data/fiuba_entrenamiento/gian/no-postulaciones/7.csv")
postulaciones2=postulaciones2.append(pd.read_csv("../../Data/fiuba_entrenamiento/gian/no-postulaciones/8.csv").sample(len(postulaciones2)//2).reset_index(drop=True))
print(len(postulaciones2))
postulaciones2

9906801

            idaviso idpostulante  sepostulo
0        1112389495       5NbOjG          0
1        1112024109      1QP841b          0
2        1112490884      96XQ6N9          0
3        1111474259      qe2QJj1          0
4        1112211292      KBzbBJm          0
5        1112328485      3NzZv26          0
6        1112474766      akDjWwE          0
7        1112312385       aZpBJW          0
8        1112285628      akDWj55          0
9        1112322843      GNd0KNN          0
10       1112355899      DrXPRJX          0
11       1112461865      8MPoBDR          0
12       1111673413       a1NjRN          0
13       1112299006      jkVWXRQ          0
14       1112501771      owz0YGW          0
15       1002543409       Ej5AAb          0
16       1112425310      KBrpAO2          0
17       1112498569      pzNMppM          0
18       1111866251       ZKqL85          0
19       1112289529      ow2awXr          0
20       1112493109      5mP1DWM          0
21       1112326017      0zd9GZ9          0
22       1112242315      3NQKV6Q          0
23       1112452417      DrlVEwW          0
24       1112402816      mzdk9dZ          0
25       1112359100      3NP46xq          0
26       1112410555      bOVKA32          0
27       1112511403      mzdlAQO          0
28       1111272539      6rPpNM4          0
29       1111591317      6rP4K13          0
...             ...          ...        ...
3302237  1112247895      0zNoaQq          0
3302238  1112460021       8PPkV3          0
3302239  1112356174      W9WXZ6R          0
3302240  1111109704      6rPzYkv          0
3302241  1112359281       8oBbGM          0
3302242  1112417725      6r2LQQL          0
3302243  1112476907       aEK1WZ          0
3302244  1112459087      96ZmkpZ          0
3302245  1112284425      LNKAJaQ          0
3302246  1112464708      NzjK61L          0
3302247  1112428763      BmBPNr0          0
3302248  1111582454      akjYpoq          0
3302249  1112466205      xk9dW3b          0
3302250  1112187863      KBAJxPA          0
3302251  1112448550      mzVKNME          0
3302252  1112495211      LN8vGRQ          0
3302253  1111917217      1QP1mWR          0
3302254  1112177777      akDLdVq          0
3302255  1112261600      KBdNvjA          0
3302256  1112338261      vV3ZvqQ          0
3302257  1112470631       Y1dLdJ          0
3302258  1112487364      lD5qAD8          0
3302259  1112493458      EzeoZ2b          0
3302260  1112272847       6adqAR          0
3302261  1112457272      QNPZLw5          0
3302262  1112463607      Nzr8lKV          0
3302263  1112316560       5QemZp          0
3302264  1112326244      6rMX1Vl          0
3302265  1112242130      DrJK2vL          0
3302266  1112246223      5mrbBmv          0

[9906801 rows x 3 columns]

In [15]:
postulaciones.head()

      idaviso idpostulante  sepostulo
0  1112257047         NM5M          1
1  1111920714         NM5M          1
2  1112346945         NM5M          1
3  1112345547         NM5M          1
4  1112237522         5awk          1

In [16]:
postulaciones=postulaciones.append(postulaciones2, ignore_index=True)
print(len(postulaciones))
postulaciones2=0
gc.collect()
postulaciones.drop_duplicates(['idaviso','idpostulante'],keep='first',inplace=True)
print(len(postulaciones))

16511335
16501951

In [17]:
postulaciones=pd.merge(postulaciones,postulantes,on='idpostulante')
postulaciones=pd.merge(postulaciones,avisos,on='idaviso')
postulaciones=pd.merge(postulaciones,avisos_no_one_hot,on='idaviso')
postulaciones=pd.merge(postulaciones,vistas,on=['idpostulante'],how='left')
postulaciones=pd.merge(postulaciones,vistas2,on=['idaviso','idpostulante'],how='left')
postulaciones=pd.merge(postulaciones,vistas3,on=['idaviso','idpostulante'],how='left')
postulaciones.sample(20)

,idaviso,idpostulante,sepostulo,edad,sexo_FEM,sexo_MASC,sexo_NO_DECLARA,Doctorado_Abandonado,Doctorado_En Curso,Doctorado_Graduado,...,nivel_laboral_Jefe / Supervisor / Responsable,nivel_laboral_Junior,nivel_laboral_Otro,nivel_laboral_Senior / Semi-Senior,tipo_de_trabajo,nivel_laboral,nombre_area_aux,vistas_postulante,vistas_al_aviso,cantidad
1081149,1112299531,BmD9aR2,1,26.0,True,False,False,False,False,False,...,False,True,False,False,Part-time,Junior,Telemarketing,15.0,NaN,NaN
6263823,1112210707,EbqlB6,0,66.0,False,True,False,False,False,False,...,False,True,False,False,Full-time,Junior,Legal,1.0,NaN,NaN
228990,1112458756,xka9mra,1,22.0,True,False,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Recepcionista,645.0,2.0,0.003101
6315785,1112337991,Bm5x02R,0,200.0,False,True,False,False,False,False,...,False,False,True,False,Part-time,Otro,Tesorería,4.0,NaN,NaN
14392418,1111874250,owjBKRe,0,22.0,True,False,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Tesorería,105.0,NaN,NaN
8400879,1112288039,ZBmNqb,1,32.0,True,False,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Ventas,102.0,NaN,NaN
8893879,1111447609,zvaNML5,0,22.0,False,True,False,False,False,False,...,False,False,True,False,Full-time,Otro,Servicios,7.0,NaN,NaN
7124663,1112211952,PmJQ5ZE,1,32.0,True,False,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Producto,NaN,NaN,NaN
14083983,1112262457,lD53aVM,0,26.0,False,True,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Soporte Técnico,3.0,NaN,NaN
4460639,1112269813,6r2GVGj,1,30.0,False,True,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Créditos y Cobranzas,6.0,NaN,NaN
13089814,1111570883,8km64x,0,50.0,False,True,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Mantenimiento,3.0,NaN,NaN
10787993,1111928374,LND6Vzj,0,27.0,False,True,False,False,False,False,...,True,False,False,False,Full-time,Jefe / Supervisor / Responsable,Ventas,65.0,NaN,NaN
4289622,1112456055,3NPA4Gr,0,21.0,True,False,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Tesorería,8.0,NaN,NaN
1900707,1112243409,ZOQj1Z,0,30.0,False,True,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Calidad,7.0,NaN,NaN
569873,1112335938,vVDvWDj,1,21.0,True,False,False,False,False,False,...,False,True,False,False,Full-time,Junior,Administración,648.0,NaN,NaN
3864053,1112401005,0zPNPPv,0,200.0,False,True,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Ingeniería Eléctrica y Electrónica,5.0,NaN,NaN
4032494,1112312211,ZD2081P,1,25.0,False,True,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Producción,872.0,NaN,NaN
10737509,1111196277,jkVKe86,0,24.0,True,False,False,False,False,False,...,False,False,True,False,Full-time,Otro,Producción,20.0,NaN,NaN
16004359,1112357810,kPLzkWW,0,35.0,False,True,False,False,False,False,...,False,True,False,False,Full-time,Junior,Internet,NaN,NaN,NaN
7621327,1112196209,xkvvKpP,0,29.0,False,True,False,False,False,False,...,False,False,False,True,Full-time,Senior / Semi-Senior,Comercial,6.0,NaN,NaN

In [18]:
postulaciones.cantidad=postulaciones.cantidad.fillna(0)
postulaciones['cantidad']=postulaciones['cantidad'].fillna(0)
postulaciones['vistas_postulante']=postulaciones['vistas_postulante'].fillna(0)
postulaciones['vistas_al_aviso']=postulaciones['vistas_al_aviso'].fillna(0)
postulaciones['lo_vio']=(postulaciones['vistas_al_aviso']>0)
postulaciones.sample(20)

,idaviso,idpostulante,sepostulo,edad,sexo_FEM,sexo_MASC,sexo_NO_DECLARA,Doctorado_Abandonado,Doctorado_En Curso,Doctorado_Graduado,...,nivel_laboral_Junior,nivel_laboral_Otro,nivel_laboral_Senior / Semi-Senior,tipo_de_trabajo,nivel_laboral,nombre_area_aux,vistas_postulante,vistas_al_aviso,cantidad,lo_vio
9899797,1112384297,1QrW1pE,0,25.0,True,False,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Transporte,301.0,0.0,0.0,False
11726692,1112231595,QNLEQYW,1,40.0,False,True,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Producción,4.0,0.0,0.0,False
15229663,1112047255,2zPEjVa,0,20.0,True,False,False,False,False,False,...,True,False,False,Full-time,Junior,Ventas,0.0,0.0,0.0,False
3018257,1112334791,A3Dr1xj,1,20.0,True,False,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Comercial,213.0,0.0,0.0,False
10404602,1112490878,5mPQpBZ,0,29.0,False,True,False,False,False,False,...,True,False,False,Full-time,Junior,Producto,3.0,0.0,0.0,False
8007351,1112295952,X958Bdb,0,200.0,False,False,True,False,False,False,...,False,True,False,Full-time,Otro,Ventas,7.0,0.0,0.0,False
676607,1112371348,86xB9R,0,28.0,True,False,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Ventas,0.0,0.0,0.0,False
14783524,1112180077,0zrNlVq,0,30.0,False,True,False,False,False,False,...,True,False,False,Full-time,Junior,Atención al Cliente,3.0,0.0,0.0,False
14170756,1112378666,6rP12pM,1,24.0,False,True,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Comercial,31.0,0.0,0.0,False
5835504,1112359379,PmLPQ1j,1,29.0,False,True,False,False,False,False,...,True,False,False,Full-time,Junior,Comercial,10.0,0.0,0.0,False
125911,1112399636,8MPAexW,0,30.0,True,False,False,False,False,False,...,True,False,False,Full-time,Junior,Comercial,0.0,0.0,0.0,False
4026651,1112100228,Dr6lkLa,0,25.0,False,True,False,False,False,False,...,False,False,False,Full-time,-,Atención al Cliente,56.0,0.0,0.0,False
1734901,1112339449,pzN39jr,1,30.0,True,False,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Recepcionista,44.0,0.0,0.0,False
7232787,1112423240,X9k1DdO,0,25.0,True,False,False,False,False,False,...,False,False,False,Full-time,-,Administración,2.0,0.0,0.0,False
15263884,1112224047,Oqb52er,0,38.0,False,True,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Administración,0.0,0.0,0.0,False
1423585,1112100114,OqNK2kv,0,49.0,True,False,False,False,False,False,...,True,False,False,Full-time,Junior,Producción,5.0,0.0,0.0,False
7568947,1112407117,BmB1Z9L,0,21.0,True,False,False,False,False,False,...,False,False,False,Full-time,Jefe / Supervisor / Responsable,Construcción,0.0,0.0,0.0,False
10738876,1112179527,MVrezav,1,20.0,True,False,False,False,False,False,...,False,True,False,Part-time,Otro,Recepcionista,0.0,0.0,0.0,False
1576765,1112369956,5P6dMw,0,34.0,True,False,False,False,False,False,...,False,False,True,Full-time,Senior / Semi-Senior,Contabilidad,2.0,0.0,0.0,False
10895793,1111989829,1ZrrJE,1,28.0,True,False,False,False,False,False,...,True,False,False,Full-time,Junior,Cadetería,89.0,0.0,0.0,False

In [19]:
postulaciones_por_area=postulaciones.copy()
postulaciones_por_area=postulaciones_por_area.groupby(by=['idpostulante','nombre_area_aux'],as_index=False).agg({'sepostulo':'count'})
postulaciones_por_area=postulaciones_por_area.rename(columns={'sepostulo':'postulaciones_misma_area'})
postulaciones_por_area.head()

  idpostulante                  nombre_area_aux  postulaciones_misma_area
0      0z5Dmrd                   Abastecimiento                         1
1      0z5Dmrd                   Administración                         2
2      0z5Dmrd       Administración de Personal                         1
3      0z5Dmrd  Almacén / Depósito / Expedición                         2
4      0z5Dmrd              Atención al Cliente                         1

In [20]:
postulaciones_por_nivel=postulaciones.copy()
postulaciones_por_nivel=postulaciones_por_nivel.groupby(by=['idpostulante','nivel_laboral'],as_index=False).agg({'sepostulo':'count'})
postulaciones_por_nivel=postulaciones_por_nivel.rename(columns={'sepostulo':'postulaciones_mismo_nivel'})
postulaciones_por_nivel.head()

,idpostulante,nivel_laboral,postulaciones_mismo_nivel
0,0z5Dmrd,-,1
1,0z5Dmrd,Gerencia / Alta Gerencia / Dirección,2
2,0z5Dmrd,Junior,4
3,0z5Dmrd,Otro,1
4,0z5Dmrd,Senior / Semi-Senior,17

In [21]:
postulaciones_por_tipo=postulaciones.copy()
postulaciones_por_tipo=postulaciones_por_tipo.groupby(by=['idpostulante','tipo_de_trabajo'],as_index=False).agg({'sepostulo':'count'})
postulaciones_por_tipo=postulaciones_por_tipo.rename(columns={'sepostulo':'postulaciones_mismo_tipo'})
postulaciones_por_tipo.head()

  idpostulante tipo_de_trabajo  postulaciones_mismo_tipo
0      0z5Dmrd       Full-time                        24
1      0z5Dmrd       Part-time                         1
2      0z5JW1r       Full-time                        26
3      0z5JW1r       Part-time                         1
4      0z5VvGv       Full-time                        55

In [22]:
postulaciones=pd.merge(postulaciones,postulaciones_por_area,on=['idpostulante','nombre_area_aux'],how='left')
postulaciones=pd.merge(postulaciones,postulaciones_por_tipo,on=['idpostulante','tipo_de_trabajo'],how='left')
postulaciones=pd.merge(postulaciones,postulaciones_por_nivel,on=['idpostulante','nivel_laboral'],how='left')
postulaciones['postulaciones_misma_area']=postulaciones['postulaciones_misma_area'].fillna(0).apply(lambda x: x if(x<=0) else x-1)
postulaciones['postulaciones_mismo_nivel']=postulaciones['postulaciones_mismo_nivel'].fillna(0).apply(lambda x: x if(x<=0) else x-1)
postulaciones['postulaciones_mismo_tipo']=postulaciones['postulaciones_mismo_tipo'].fillna(0).apply(lambda x: x if(x<=0) else x-1)
postulaciones=pd.merge(postulaciones,vistas_por_area,on=['idpostulante','nombre_area_aux'],how='left')
postulaciones=pd.merge(postulaciones,vistas_por_tipo,on=['idpostulante','tipo_de_trabajo'],how='left')
postulaciones=pd.merge(postulaciones,vistas_por_nivel,on=['idpostulante','nivel_laboral'],how='left')
postulaciones['vistas_por_area']=postulaciones['vistas_por_area'].fillna(0)
postulaciones['vistas_por_tipo']=postulaciones['vistas_por_tipo'].fillna(0)
postulaciones['vistas_por_nivel']=postulaciones['vistas_por_tipo'].fillna(0)
postulaciones.sample(20)

,idaviso,idpostulante,sepostulo,edad,sexo_FEM,sexo_MASC,sexo_NO_DECLARA,Doctorado_Abandonado,Doctorado_En Curso,Doctorado_Graduado,...,vistas_postulante,vistas_al_aviso,cantidad,lo_vio,postulaciones_misma_area,postulaciones_mismo_tipo,postulaciones_mismo_nivel,vistas_por_area,vistas_por_tipo,vistas_por_nivel
14761201,1112397991,xkv48Lb,1,36.0,False,True,False,False,False,False,...,747.0,0.0,0.000000,False,293,1030,869,247.0,670.0,670.0
5546374,1112367965,RzPkaXZ,1,27.0,True,False,False,False,False,False,...,37.0,0.0,0.000000,False,3,25,23,0.0,34.0,34.0
8035040,1112388033,KBaON9Q,1,24.0,True,False,False,False,False,False,...,134.0,0.0,0.000000,False,3,23,12,0.0,76.0,76.0
948964,1112335063,6rPxRA4,0,23.0,False,True,False,False,False,False,...,6.0,0.0,0.000000,False,0,18,15,0.0,6.0,6.0
15700866,1112334849,Nj8rM,0,44.0,True,False,False,False,False,False,...,10.0,0.0,0.000000,False,2,1,2,0.0,0.0,0.0
15691165,1111698092,ow50Jvk,0,24.0,True,False,False,False,False,False,...,249.0,0.0,0.000000,False,0,45,37,8.0,160.0,160.0
11872600,1112115647,Nzrrk4M,0,20.0,True,False,False,False,False,False,...,0.0,0.0,0.000000,False,1,20,11,0.0,0.0,0.0
2040037,1112394664,Bm51VZv,0,35.0,False,True,False,False,False,False,...,0.0,0.0,0.000000,False,0,49,2,0.0,0.0,0.0
15314161,1111466360,MV6O4ex,0,19.0,False,True,False,False,False,False,...,13.0,0.0,0.000000,False,5,34,20,2.0,7.0,7.0
7218892,1112402896,QNr9JJ5,1,31.0,True,False,False,False,False,False,...,88.0,1.0,0.011364,True,17,38,5,29.0,49.0,49.0
9932474,1112208898,8M2BleL,0,53.0,False,True,False,False,False,False,...,6.0,0.0,0.000000,False,0,21,18,0.0,6.0,6.0
13883216,1112484981,A36KVxm,0,31.0,False,True,False,False,False,False,...,19.0,0.0,0.000000,False,1,3,1,0.0,1.0,1.0
10664732,1112349019,BmVp8NE,0,29.0,True,False,False,False,False,False,...,36.0,0.0,0.000000,False,0,20,18,0.0,32.0,32.0
15420153,1112219324,Z3MDD1,0,28.0,True,False,False,False,False,False,...,2.0,0.0,0.000000,False,0,16,8,0.0,2.0,2.0
13931121,1111709712,Bm5QQKw,0,43.0,False,True,False,False,False,False,...,8.0,0.0,0.000000,False,0,13,10,0.0,8.0,8.0
1001611,1112386779,EzEP5vN,0,27.0,False,True,False,False,False,False,...,4.0,0.0,0.000000,False,1,20,0,0.0,4.0,4.0
13232808,1112221462,ow2ZzRe,0,24.0,False,True,False,False,False,False,...,52.0,0.0,0.000000,False,1,69,42,0.0,41.0,41.0
11143230,1112274484,xkvemv0,0,32.0,False,True,False,False,False,False,...,5.0,0.0,0.000000,False,0,18,13,0.0,5.0,5.0
9625584,1112314005,rme0wPb,1,27.0,False,True,False,False,False,False,...,331.0,0.0,0.000000,False,34,289,79,23.0,310.0,310.0
5219035,1112272708,8M2PLzD,1,43.0,False,True,False,False,False,False,...,27.0,2.0,0.074074,True,30,62,2,19.0,25.0,25.0

In [23]:
areas=postulaciones.nombre_area.value_counts().index
means={}
for area in areas:
    mean=postulaciones[postulaciones['nombre_area']==area].sepostulo.mean()
    print("Area "+area+" :"+str(mean))
    means[area]=mean
postulaciones['nombre_area']=postulaciones["nombre_area"].replace(means)
postulaciones['nombre_area'].sample(10)

Area Ventas :0.4107671095273288
Area Administración :0.4655828604612842
Area Comercial :0.3840586368487641
Area Producción :0.45768417671436445
Area Atención al Cliente :0.6060249773511499
Area Recepcionista :0.718280259734746
Area Contabilidad :0.27154888441221453
Area Call Center :0.6232275489534098
Area Programación :0.037914594760855076
Area Tecnologia / Sistemas :0.09991994274693417
Area Almacén / Depósito / Expedición :0.4376031681129132
Area Telemarketing :0.5909094364580403
Area Mantenimiento :0.19297955796647676
Area Recursos Humanos :0.3547399538250343
Area Tesorería :0.619875065111674
Area Logística :0.3540975899440788
Area Gastronomia :0.36279507878407297
Area Mantenimiento y Limpieza :0.5040221604747693
Area Soporte Técnico :0.2559524401771056
Area Oficios y Profesiones :0.21838131818133721
Area Marketing :0.3343335238458119
Area Administración de Personal :0.381920143066886
Area Compras :0.3153867193435648
Area Créditos y Cobranzas :0.42451058093746297
Area Finanzas :0.3226692875481386
Area Legal :0.39232518399913885
Area Transporte :0.23900131369315483
Area Otros :0.2646239946003712
Area Seguridad :0.3312393127894262
Area Secretaria :0.6730432194702556
Area Salud :0.25875372453109663
Area Selección :0.343026317004905
Area Desarrollo de Negocios :0.23926975373205286
Area Calidad :0.25901130354630575
Area Impuestos :0.2151604128408834
Area Farmacéutica :0.5012796661561707
Area Ingeniería  Industrial :0.3541668839363
Area Medicina :0.15115066035177033
Area Camareros :0.5692136430407638
Area Jóvenes Profesionales :0.4558916835262711
Area Construcción :0.23475174568882373
Area Control de Gestión :0.28774959671406686
Area Abastecimiento :0.31802974500267084
Area Análisis Funcional :0.131104602039092
Area Auditoría :0.22987562435442108
Area Cadetería :0.4978411917765133
Area Arquitectura :0.28765516142581943
Area Distribución :0.3361197230029264
Area Servicios :0.3215380125492485
Area Telecomunicaciones :0.14863966187358682
Area Ingeniería  Mecánica :0.2151311172079372
Area Facturación :0.4198004475628018
Area Compras Internacionales/Importación :0.3549125305126119
Area Programación de producción :0.2571717853526831
Area Planeamiento comercial :0.2943471521975379
Area Ingeniería  Eléctrica y Electrónica :0.17108774695061882
Area Asistente :0.6180934579439252
Area Testing / QA / QC :0.07724429868049729
Area Producto :0.30223751489754336
Area Gerencia / Dirección General :0.256162061712512
Area Laboratorio :0.2867683869142198
Area Consultorías Comercio Exterior :0.3804541011285879
Area Liderazgo de Proyecto :0.13730068717059177
Area Hotelería :0.4513813651137595
Area Sistemas :0.14966279888280842
Area Otras Ingenierias :0.20655394011211886
Area Mineria/Petroleo/Gas :0.19962939206043762
Area Pasantía / Trainee :0.543960244648318
Area Ingeniería Civil :0.20796777302721003
Area Diseño Gráfico :0.3883327757906384
Area Redes :0.18288091414128116
Area Business Intelligence :0.26065971574091357
Area Capacitación :0.29323774357868637
Area Comunicacion :0.4880829305093744
Area Ingeniería Oficina Técnica / Proyecto :0.27804224508993475
Area Análisis de Riesgos :0.4129344101811062
Area Infraestructura :0.14444724727249794
Area Data Entry :0.43004879940535823
Area Ventas Internacionales/Exportación :0.40059002916998143
Area Dirección de Obra :0.2174767631675384
Area Ingeniería Química :0.29216796809544554
Area Seguridad e Higiene :0.3521412624314999
Area Tecnologías de la Información :0.10311643835616438
Area Caja :0.6095863660571631
Area Compensación y Planilla :0.2388242058358488
Area Community Management :0.4565627594535437
Area Turismo :0.25548387096774194
Area Seguros :0.45227600881525953
Area Ingeniería Electromecánica :0.21123595505617979
Area Ingeniería de Procesos :0.3350979772439949
Area Consultoria :0.2701844135484137
Area E-commerce :0.353294934778926
Area Relaciones Institucionales/Publicas :0.48693122612018064
Area Administracion de Seguros :0.4011666154993202
Area Cuentas Corrientes :0.3439670811026061
Area Educación/ Docentes :0.2099897109718455
Area Organización y Métodos :0.24876936628840873
Area Ingeniería en Alimentos :0.27714670255720053
Area Planeamiento económico-financiero :0.283727630339631
Area Seguridad Informática :0.1584299732381802
Area Asistente de Tráfico :0.4174907661146193
Area Ingeniería  Automotriz :0.17357222844344905
Area Venta de Seguros :0.41502148595628074
Area Ingeniería Agrónoma :0.1729347271800102
Area Corporate Finance / Banca Inversión :0.2833431690764237
Area Educación :0.25705162320383185
Area Ingeniería de Ventas :0.1901887369144953
Area Estética y Cuidado Personal :0.06317007327419977
Area Operaciones :0.1839405444704742
Area Administración de Base de Datos :0.16452780519907864
Area Inversiones / Proyectos de Inversión :0.4899497487437186
Area Diseño Industrial :0.1029102048631055
Area Diseño :0.1682747973755307
Area Diseño Textil e Indumentaria :0.1811522470797862
Area Prácticas Profesionales :0.16747084841174106
Area Media Planning :0.2979747118719928
Area Evaluación Económica :0.31207100591715975
Area Ingeniería de Producto :0.26109134045077104
Area Comercio Exterior :0.1387772078192153
Area Ingeniería  Metalurgica :0.16024456135361864
Area Seguridad Industrial :0.3276034952012606
Area Bioquímica :0.18752783964365255
Area Comunicaciones Externas :0.6556765627331046
Area Planeamiento :0.17529039070749736
Area Otras áreas técnicas en salud :0.27505330490405117
Area Farmacia industrial :0.21013250194855806
Area Internet :0.10317883146865565
Area Promotoras/es :0.3703374777975133
Area Diseño Web :0.22711680808810256
Area Diseño de Interiores / Decoración :0.3587174348697395
Area Quimica :0.2121490181684713
Area Back Office :0.3504509479109148
Area Farmacia comercial :0.35165243223171183
Area Otras Especialidades médicas :0.4115980355119003
Area Tecnico de Seguros :0.31417399804496576
Area Creatividad :0.3025953598112466
Area Química :0.24605543710021321
Area Dirección :0.1891828611566378
Area Veterinaria :0.084328882642305
Area Medio Ambiente :0.16710557816614796
Area Comunicaciones Internas :0.3995880535530381
Area Ingeniería en Petróleo y Petroquímica :0.3015995872033024
Area Investigación y Desarrollo :0.11605900361814639
Area Apoderado Aduanal :0.3526434195725534
Area Ingeniería en Minas :0.12633279483037158
Area Diseño Multimedia :0.21861684693543101
Area Bioquimica :0.21337792642140468
Area Asesoría Legal Internacional :0.4720603359616044
Area Finanzas Internacionales :0.31484671029968997
Area Independientes :0.15096398690432886
Area Data Warehousing :0.2484076433121019
Area Emergentología :0.03938286642306131
Area Negocios Internacionales :0.291213768115942
Area Multimedia :0.2829931972789116
Area Responsabilidad Social :0.09045454545454545
Area Auditoría Médica :0.14071696094168004
Area Periodismo :0.14702702702702702
Area Instrumentación :0.14937533948940793
Area Medicina Laboral :0.33070866141732286
Area Telefonista :0.30760095011876487
Area Topografía :0.035206917850525016
Area Bienestar Estudiantil :0.5068664169787765
Area Arte y Cultura :0.1688951442646024
Area Trabajo social :0.15573179524152847
Area Ingeniería Geológica :0.0967016491754123
Area Trabajo Social :0.08236208236208237
Area Kinesiología / terapia ocupacional :0.028901734104046242
Area Clínica Médica :0.024958402662229616
Area Psicología :0.007738607050730868
Area Traduccion :0.0017211703958691911
Area Mercadotecnia Internacional :0.2627118644067797
Area Diseño 3D :0.24045801526717558
Area Exploración Minera y Petroquimica :0.23000987166831194
Area Idiomas :0.18448637316561844
Area Instrumentación quirúrgica :0.15460526315789475
Area Educación especial :0.10935738444193913
Area Urbanismo :0.015931372549019607
Area Enfermería (ver Enfermería) :0.0
Area Odontología :0.0038510911424903724
Area Instrumentación Minera :0.30824372759856633
Area Cuidados Intensivos Cardiologicos Adultos :0.15486725663716813
Area Diagnóstico por imágenes :0.10022779043280182
Area Farmacia hospitalaria :0.04225352112676056
Area Esterilización :0.0343980343980344
Area Prácticas cardiológicas :0.03
Area Fonoaudiología :0.0025188916876574307
Area Maternidad :0.022900763358778626
Area Auditoría de Seguros :0.0

7149228     0.465583
14365270    0.257052
6279974     0.354740
14764123    0.501280
7598118     0.257172
10678908    0.392325
14795711    0.410767
8446650     0.457684
10962060    0.277147
10998523    0.410767
Name: nombre_area, dtype: float64

In [24]:
train, test=train_test_split(postulaciones.sample(2*(len(postulaciones)//3)),test_size=0.05)
print("Train: ",len(train),"Test: ",len(test))
features=list(postulaciones.columns)
features.remove('idaviso')
features.remove('idpostulante')
features.remove('sepostulo')
features.remove('titulo')
features.remove('denominacion_empresa')
features.remove('nombre_area_aux')
features.remove('tipo_de_trabajo')
features.remove('nivel_laboral')

x_train=train[features]
y_train=train['sepostulo']

x_test=test[features]
y_test=test['sepostulo']
postulaciones=0

Train:  10187879 Test:  536205

In [25]:
c=0
gc.collect()

55

In [26]:
c=XGBClassifier(objective='binary:logistic',max_depth=18,learning_rate=0.1,subsample=0.8,colsample_bytree=0.8,n_estimators=1200,silent=False,n_jobs=-1,verbose=1)
#c = joblib.load("../../Data/fiuba_entrenamiento/gian/modelos/....pkl")
dt=c.fit(x_train,y_train,eval_set=[(x_test,y_test)],verbose=True,early_stopping_rounds=50)

[0]	validation_0-error:0.099165
Will train until validation_0-error hasn't improved in 50 rounds.
[1]	validation_0-error:0.09433
[2]	validation_0-error:0.094343
[3]	validation_0-error:0.093281
[4]	validation_0-error:0.092556
[5]	validation_0-error:0.091562
[6]	validation_0-error:0.091383
[7]	validation_0-error:0.091014
[8]	validation_0-error:0.091081
[9]	validation_0-error:0.090409
[10]	validation_0-error:0.090094
[11]	validation_0-error:0.090309
[12]	validation_0-error:0.089671
[13]	validation_0-error:0.0899
[14]	validation_0-error:0.089438
[15]	validation_0-error:0.08896
[16]	validation_0-error:0.08899
[17]	validation_0-error:0.088509
[18]	validation_0-error:0.087992
[19]	validation_0-error:0.087661
[20]	validation_0-error:0.087649
[21]	validation_0-error:0.087567
[22]	validation_0-error:0.087625
[23]	validation_0-error:0.08726
[24]	validation_0-error:0.086961
[25]	validation_0-error:0.086957
[26]	validation_0-error:0.08656
[27]	validation_0-error:0.086053
[28]	validation_0-error:0.085958
[29]	validation_0-error:0.085478
[30]	validation_0-error:0.085092
[31]	validation_0-error:0.084753
[32]	validation_0-error:0.084505
[33]	validation_0-error:0.08408
[34]	validation_0-error:0.08383
[35]	validation_0-error:0.083408
[36]	validation_0-error:0.08333
[37]	validation_0-error:0.082771
[38]	validation_0-error:0.082509
[39]	validation_0-error:0.082275
[40]	validation_0-error:0.081818
[41]	validation_0-error:0.081659
[42]	validation_0-error:0.081428
[43]	validation_0-error:0.081387
[44]	validation_0-error:0.081193
[45]	validation_0-error:0.08117
[46]	validation_0-error:0.080967
[47]	validation_0-error:0.080749
[48]	validation_0-error:0.080557
[49]	validation_0-error:0.080385
[50]	validation_0-error:0.080339
[51]	validation_0-error:0.080193
[52]	validation_0-error:0.07988
[53]	validation_0-error:0.079835
[54]	validation_0-error:0.079727
[55]	validation_0-error:0.079671
[56]	validation_0-error:0.07935
[57]	validation_0-error:0.079289
[58]	validation_0-error:0.079223
[59]	validation_0-error:0.079093
[60]	validation_0-error:0.078985
[61]	validation_0-error:0.078843
[62]	validation_0-error:0.078791
[63]	validation_0-error:0.078716
[64]	validation_0-error:0.078656
[65]	validation_0-error:0.078561
[66]	validation_0-error:0.078477
[67]	validation_0-error:0.078436
[68]	validation_0-error:0.078371
[69]	validation_0-error:0.078179
[70]	validation_0-error:0.07806
[71]	validation_0-error:0.077966
[72]	validation_0-error:0.077884
[73]	validation_0-error:0.07781
[74]	validation_0-error:0.077668
[75]	validation_0-error:0.07764
[76]	validation_0-error:0.07756
[77]	validation_0-error:0.077554
[78]	validation_0-error:0.077457
[79]	validation_0-error:0.077329
[80]	validation_0-error:0.077319
[81]	validation_0-error:0.077286
[82]	validation_0-error:0.077276
[83]	validation_0-error:0.077211
[84]	validation_0-error:0.076976
[85]	validation_0-error:0.07695
[86]	validation_0-error:0.07693
[87]	validation_0-error:0.076935
[88]	validation_0-error:0.076706
[89]	validation_0-error:0.076642
[90]	validation_0-error:0.076612
[91]	validation_0-error:0.076504
[92]	validation_0-error:0.076374
[93]	validation_0-error:0.076206
[94]	validation_0-error:0.076217
[95]	validation_0-error:0.076187
[96]	validation_0-error:0.076133
[97]	validation_0-error:0.076128
[98]	validation_0-error:0.076003
[99]	validation_0-error:0.075973
[100]	validation_0-error:0.075936
[101]	validation_0-error:0.075932
[102]	validation_0-error:0.075893
[103]	validation_0-error:0.075865
[104]	validation_0-error:0.075863
[105]	validation_0-error:0.075646
[106]	validation_0-error:0.075617
[107]	validation_0-error:0.075618
[108]	validation_0-error:0.075548
[109]	validation_0-error:0.075557
[110]	validation_0-error:0.075486
[111]	validation_0-error:0.075288
[112]	validation_0-error:0.075186
[113]	validation_0-error:0.075216
[114]	validation_0-error:0.075175
[115]	validation_0-error:0.075184
[116]	validation_0-error:0.075188
[117]	validation_0-error:0.07507
[118]	validation_0-error:0.075057
[119]	validation_0-error:0.075005
[120]	validation_0-error:0.074928
[121]	validation_0-error:0.074833
[122]	validation_0-error:0.074817
[123]	validation_0-error:0.074764
[124]	validation_0-error:0.074757
[125]	validation_0-error:0.074749
[126]	validation_0-error:0.074712
[127]	validation_0-error:0.074662
[128]	validation_0-error:0.07466
[129]	validation_0-error:0.074615
[130]	validation_0-error:0.074611
[131]	validation_0-error:0.074567
[132]	validation_0-error:0.074503
[133]	validation_0-error:0.074406
[134]	validation_0-error:0.074367
[135]	validation_0-error:0.074259
[136]	validation_0-error:0.074192
[137]	validation_0-error:0.074192
[138]	validation_0-error:0.0741
[139]	validation_0-error:0.0741
[140]	validation_0-error:0.074097
[141]	validation_0-error:0.074108
[142]	validation_0-error:0.074138
[143]	validation_0-error:0.074117
[144]	validation_0-error:0.074005
[145]	validation_0-error:0.073994
[146]	validation_0-error:0.073977
[147]	validation_0-error:0.073903
[148]	validation_0-error:0.07388
[149]	validation_0-error:0.073845
[150]	validation_0-error:0.073828
[151]	validation_0-error:0.073845
[152]	validation_0-error:0.073795
[153]	validation_0-error:0.073813
[154]	validation_0-error:0.073847
[155]	validation_0-error:0.073789
[156]	validation_0-error:0.073808
[157]	validation_0-error:0.073815
[158]	validation_0-error:0.073761
[159]	validation_0-error:0.073733
[160]	validation_0-error:0.073731
[161]	validation_0-error:0.073703
[162]	validation_0-error:0.073742
[163]	validation_0-error:0.073705
[164]	validation_0-error:0.073692
[165]	validation_0-error:0.073657
[166]	validation_0-error:0.073653
[167]	validation_0-error:0.07364
[168]	validation_0-error:0.073612
[169]	validation_0-error:0.073565
[170]	validation_0-error:0.073569
[171]	validation_0-error:0.07356
[172]	validation_0-error:0.073537
[173]	validation_0-error:0.073491
[174]	validation_0-error:0.073412
[175]	validation_0-error:0.073408
[176]	validation_0-error:0.07339
[177]	validation_0-error:0.073373
[178]	validation_0-error:0.073407
[179]	validation_0-error:0.073405
[180]	validation_0-error:0.073392
[181]	validation_0-error:0.073366
[182]	validation_0-error:0.07328
[183]	validation_0-error:0.073103
[184]	validation_0-error:0.073091
[185]	validation_0-error:0.073088
[186]	validation_0-error:0.073086
[187]	validation_0-error:0.073084
[188]	validation_0-error:0.072989
[189]	validation_0-error:0.072952
[190]	validation_0-error:0.072899
[191]	validation_0-error:0.072937
[192]	validation_0-error:0.072939
[193]	validation_0-error:0.072886
[194]	validation_0-error:0.072832
[195]	validation_0-error:0.072819
[196]	validation_0-error:0.072815
[197]	validation_0-error:0.072823
[198]	validation_0-error:0.07283
[199]	validation_0-error:0.072821
[200]	validation_0-error:0.072795
[201]	validation_0-error:0.072748
[202]	validation_0-error:0.072741
[203]	validation_0-error:0.072689
[204]	validation_0-error:0.072677
[205]	validation_0-error:0.072651
[206]	validation_0-error:0.072638
[207]	validation_0-error:0.072661
[208]	validation_0-error:0.072659
[209]	validation_0-error:0.072648
[210]	validation_0-error:0.072676
[211]	validation_0-error:0.072659
[212]	validation_0-error:0.072676
[213]	validation_0-error:0.072633
[214]	validation_0-error:0.072621
[215]	validation_0-error:0.072597
[216]	validation_0-error:0.07256
[217]	validation_0-error:0.072545
[218]	validation_0-error:0.072482
[219]	validation_0-error:0.072476
[220]	validation_0-error:0.072457
[221]	validation_0-error:0.072463
[222]	validation_0-error:0.072446
[223]	validation_0-error:0.072461
[224]	validation_0-error:0.072401
[225]	validation_0-error:0.072381
[226]	validation_0-error:0.072377
[227]	validation_0-error:0.072364
[228]	validation_0-error:0.072342
[229]	validation_0-error:0.072388
[230]	validation_0-error:0.072355
[231]	validation_0-error:0.072334
[232]	validation_0-error:0.072331
[233]	validation_0-error:0.072312
[234]	validation_0-error:0.072245
[235]	validation_0-error:0.072243
[236]	validation_0-error:0.072254
[237]	validation_0-error:0.072265
[238]	validation_0-error:0.072271
[239]	validation_0-error:0.072317
[240]	validation_0-error:0.072297
[241]	validation_0-error:0.072269
[242]	validation_0-error:0.072312
[243]	validation_0-error:0.072314
[244]	validation_0-error:0.072316
[245]	validation_0-error:0.072243
[246]	validation_0-error:0.072193
[247]	validation_0-error:0.072185
[248]	validation_0-error:0.072191
[249]	validation_0-error:0.072204
[250]	validation_0-error:0.072193
[251]	validation_0-error:0.072232
[252]	validation_0-error:0.072243
[253]	validation_0-error:0.072291
[254]	validation_0-error:0.072275
[255]	validation_0-error:0.072297
[256]	validation_0-error:0.072269
[257]	validation_0-error:0.072297
[258]	validation_0-error:0.072319
[259]	validation_0-error:0.072334
[260]	validation_0-error:0.072364
[261]	validation_0-error:0.072366
[262]	validation_0-error:0.072359
[263]	validation_0-error:0.072381
[264]	validation_0-error:0.072353
[265]	validation_0-error:0.072301
[266]	validation_0-error:0.072276
[267]	validation_0-error:0.072297
[268]	validation_0-error:0.07231
[269]	validation_0-error:0.07236
[270]	validation_0-error:0.072347
[271]	validation_0-error:0.072336
[272]	validation_0-error:0.072286
[273]	validation_0-error:0.072258
[274]	validation_0-error:0.072232
[275]	validation_0-error:0.072222
[276]	validation_0-error:0.072219
[277]	validation_0-error:0.072234
[278]	validation_0-error:0.072181
[279]	validation_0-error:0.072213
[280]	validation_0-error:0.072222
[281]	validation_0-error:0.072209
[282]	validation_0-error:0.072262
[283]	validation_0-error:0.072239
[284]	validation_0-error:0.072124
[285]	validation_0-error:0.072122
[286]	validation_0-error:0.072142
[287]	validation_0-error:0.072114
[288]	validation_0-error:0.072109
[289]	validation_0-error:0.072109
[290]	validation_0-error:0.072081
[291]	validation_0-error:0.072086
[292]	validation_0-error:0.072055
[293]	validation_0-error:0.072075
[294]	validation_0-error:0.072071
[295]	validation_0-error:0.072086
[296]	validation_0-error:0.072083
[297]	validation_0-error:0.072105
[298]	validation_0-error:0.072075
[299]	validation_0-error:0.072116
[300]	validation_0-error:0.072112
[301]	validation_0-error:0.072058
[302]	validation_0-error:0.072083
[303]	validation_0-error:0.072088
[304]	validation_0-error:0.072
[305]	validation_0-error:0.071993
[306]	validation_0-error:0.071995
[307]	validation_0-error:0.071989
[308]	validation_0-error:0.072034
[309]	validation_0-error:0.072012
[310]	validation_0-error:0.07206
[311]	validation_0-error:0.072027
[312]	validation_0-error:0.071989
[313]	validation_0-error:0.071971
[314]	validation_0-error:0.071978
[315]	validation_0-error:0.071956
[316]	validation_0-error:0.071991
[317]	validation_0-error:0.071965
[318]	validation_0-error:0.071954
[319]	validation_0-error:0.071959
[320]	validation_0-error:0.071963
[321]	validation_0-error:0.071969
[322]	validation_0-error:0.07193
[323]	validation_0-error:0.071969
[324]	validation_0-error:0.071997
[325]	validation_0-error:0.071956
[326]	validation_0-error:0.071972
[327]	validation_0-error:0.071997
[328]	validation_0-error:0.071987
[329]	validation_0-error:0.072014
[330]	validation_0-error:0.071989
[331]	validation_0-error:0.071969
[332]	validation_0-error:0.071995
[333]	validation_0-error:0.071987
[334]	validation_0-error:0.07203
[335]	validation_0-error:0.072047
[336]	validation_0-error:0.072056
[337]	validation_0-error:0.072062
[338]	validation_0-error:0.072058
[339]	validation_0-error:0.072038
[340]	validation_0-error:0.072036
[341]	validation_0-error:0.072096
[342]	validation_0-error:0.072103
[343]	validation_0-error:0.072077
[344]	validation_0-error:0.072103
[345]	validation_0-error:0.072099
[346]	validation_0-error:0.072138
[347]	validation_0-error:0.072118
[348]	validation_0-error:0.072142
[349]	validation_0-error:0.07215
[350]	validation_0-error:0.072159
[351]	validation_0-error:0.072127
[352]	validation_0-error:0.072155
[353]	validation_0-error:0.072133
[354]	validation_0-error:0.07214
[355]	validation_0-error:0.072107
[356]	validation_0-error:0.07211
[357]	validation_0-error:0.072068
[358]	validation_0-error:0.072002
[359]	validation_0-error:0.072036
[360]	validation_0-error:0.072006
[361]	validation_0-error:0.072025
[362]	validation_0-error:0.07203
[363]	validation_0-error:0.072021
[364]	validation_0-error:0.072006
[365]	validation_0-error:0.072002
[366]	validation_0-error:0.072014
[367]	validation_0-error:0.072023
[368]	validation_0-error:0.07203
[369]	validation_0-error:0.072034
[370]	validation_0-error:0.072012
[371]	validation_0-error:0.071995
[372]	validation_0-error:0.071991
Stopping. Best iteration:
[322]	validation_0-error:0.07193

In [27]:
from sklearn.metrics import roc_auc_score
x_final=x_test[features]
y_final=c.predict_proba(x_final)
y_pred=[]
for elem in y_final:
    y_pred.append(elem[1])
score=roc_auc_score(y_test, y_pred)
print(score)

0.9780729532432872

In [28]:
joblib.dump(c, "../../Data/fiuba_entrenamiento/gian/modelos/XGBoost v6.pkl")

['../../Data/fiuba_entrenamiento/gian/modelos/XGBoost v6.pkl']

In [33]:
prediccion = pd.read_csv("../../Data/fiuba_entrenamiento/test_final_100k.csv")
print(len(prediccion))
prediccion=pd.merge(prediccion,postulantes,on='idpostulante',how='inner')
print(len(prediccion))
prediccion=pd.merge(prediccion,avisos,on='idaviso',how='inner')
print(len(prediccion))
prediccion=pd.merge(prediccion,avisos_no_one_hot,on='idaviso',how='inner')
print(len(prediccion))
prediccion=pd.merge(prediccion,vistas,on=['idpostulante'],how='left')
prediccion=pd.merge(prediccion,vistas2,on=['idaviso','idpostulante'],how='left')
prediccion=pd.merge(prediccion,vistas3,on=['idaviso','idpostulante'],how='left')
prediccion.cantidad=prediccion.cantidad.fillna(0)
prediccion['cantidad']=prediccion['cantidad'].fillna(0)
prediccion['vistas_postulante']=prediccion['vistas_postulante'].fillna(0)
prediccion['vistas_al_aviso']=prediccion['vistas_al_aviso'].fillna(0)
prediccion['lo_vio']=(prediccion['vistas_al_aviso']>0)
prediccion.cantidad=prediccion.cantidad.fillna(0)
prediccion=pd.merge(prediccion,vistas_por_area,on=['idpostulante','nombre_area_aux'],how='left')
prediccion=pd.merge(prediccion,vistas_por_tipo,on=['idpostulante','tipo_de_trabajo'],how='left')
prediccion=pd.merge(prediccion,vistas_por_nivel,on=['idpostulante','nivel_laboral'],how='left')
prediccion['vistas_por_area']=prediccion['vistas_por_area'].fillna(0)
prediccion['vistas_por_tipo']=prediccion['vistas_por_tipo'].fillna(0)
prediccion['vistas_por_nivel']=prediccion['vistas_por_tipo'].fillna(0)
prediccion=pd.merge(prediccion,postulaciones_por_area,on=['idpostulante','nombre_area_aux'],how='left')
prediccion=pd.merge(prediccion,postulaciones_por_tipo,on=['idpostulante','tipo_de_trabajo'],how='left')
prediccion=pd.merge(prediccion,postulaciones_por_nivel,on=['idpostulante','nivel_laboral'],how='left')
prediccion['postulaciones_misma_area']=prediccion['postulaciones_misma_area'].fillna(0)
prediccion['postulaciones_mismo_nivel']=prediccion['postulaciones_mismo_nivel'].fillna(0)
prediccion['postulaciones_mismo_tipo']=prediccion['postulaciones_mismo_tipo'].fillna(0)
prediccion.sample(10)

100000
100000
100000
100000

,id,idaviso,idpostulante,edad,sexo_FEM,sexo_MASC,sexo_NO_DECLARA,Doctorado_Abandonado,Doctorado_En Curso,Doctorado_Graduado,...,vistas_postulante,vistas_al_aviso,cantidad,lo_vio,vistas_por_area,vistas_por_tipo,vistas_por_nivel,postulaciones_misma_area,postulaciones_mismo_tipo,postulaciones_mismo_nivel
35455,82967,1112466359,vV3QlYP,26.0,False,True,False,False,False,False,...,30.0,2.0,0.066667,True,7.0,23.0,23.0,3.0,34.0,10.0
33341,60629,1112455073,W9WwE1l,27.0,True,False,False,False,False,False,...,26.0,2.0,0.076923,True,9.0,12.0,12.0,0.0,3.0,0.0
67844,13738,1112053770,EDl5Z6,43.0,True,False,False,False,False,False,...,22.0,0.0,0.000000,False,0.0,0.0,0.0,0.0,21.0,3.0
79167,26679,1112343243,EGLvkz,28.0,True,False,False,False,False,False,...,31.0,0.0,0.000000,False,9.0,24.0,24.0,11.0,50.0,3.0
14190,61822,1112455707,JBmND4r,23.0,True,False,False,False,False,False,...,15.0,1.0,0.066667,True,2.0,7.0,7.0,8.0,40.0,45.0
87200,40022,1112418455,NrooV,200.0,False,False,True,False,False,False,...,0.0,0.0,0.000000,False,0.0,0.0,0.0,3.0,16.0,1.0
45884,1951,1111169187,8wGoNL,40.0,True,False,False,False,False,False,...,0.0,0.0,0.000000,False,0.0,0.0,0.0,0.0,16.0,13.0
13641,60746,1112455080,YjVKa9X,31.0,False,True,False,False,False,False,...,0.0,0.0,0.000000,False,0.0,0.0,0.0,3.0,38.0,7.0
60693,63043,1112457151,qe20qma,25.0,False,True,False,False,False,False,...,2.0,1.0,0.500000,True,1.0,2.0,2.0,0.0,22.0,4.0
38108,1301,1110531374,vVj6LBQ,27.0,True,False,False,False,False,False,...,62.0,1.0,0.016129,True,17.0,34.0,34.0,14.0,31.0,18.0

In [34]:
prediccion['nombre_area']=prediccion["nombre_area"].replace(means)
prediccion['nombre_area'].sample(10)

51889    0.381920
31527    0.543960
3124     0.606025
69681    0.099920
12914    0.384059
20014    0.465583
42338    0.334334
71446    0.410767
12238    0.410767
24367    0.351652
Name: nombre_area, dtype: float64

In [35]:
x_final=prediccion[features]
y_final=c.predict_proba(x_final)
y_final

array([[9.1212988e-01, 8.7870114e-02],
       [9.1183382e-01, 8.8166162e-02],
       [9.8878884e-01, 1.1211162e-02],
       ...,
       [9.9955821e-01, 4.4179207e-04],
       [9.9947560e-01, 5.2438810e-04],
       [9.9984521e-01, 1.5480189e-04]], dtype=float32)

In [36]:
y_final2=[]
print(c.classes_)
print(len(y_final))
for elem in y_final:
    y_final2.append(elem[1])
print(len(y_final2))

[0 1]
100000
100000

In [37]:
prediccion['sepostulo']=y_final2

In [38]:
prediccion.head()

,id,idaviso,idpostulante,edad,sexo_FEM,sexo_MASC,sexo_NO_DECLARA,Doctorado_Abandonado,Doctorado_En Curso,Doctorado_Graduado,...,vistas_al_aviso,cantidad,lo_vio,vistas_por_area,vistas_por_tipo,vistas_por_nivel,postulaciones_misma_area,postulaciones_mismo_tipo,postulaciones_mismo_nivel,sepostulo
0,0,739260,6M9ZQR,42.0,True,False,False,False,False,True,...,0.0,0.0,False,4.0,24.0,24.0,1.0,23.0,1.0,0.087870
1,1,739260,6v1xdL,30.0,False,True,False,False,False,False,...,0.0,0.0,False,0.0,6.0,6.0,6.0,63.0,0.0,0.088166
2,2,739260,ezRKm9,36.0,True,False,False,False,False,False,...,0.0,0.0,False,1.0,7.0,7.0,3.0,16.0,2.0,0.011211
3,3,758580,1Q35ej,68.0,False,True,False,False,False,False,...,0.0,0.0,False,0.0,0.0,0.0,2.0,19.0,0.0,0.083799
4,4,758580,EAN4J6,32.0,True,False,False,False,False,False,...,0.0,0.0,False,0.0,3.0,3.0,1.0,13.0,1.0,0.000737

In [39]:
prediccion.drop(features,axis=1,inplace=True)
prediccion.drop(['idaviso','idpostulante','titulo','denominacion_empresa'],axis=1,inplace=True)
prediccion.drop(['tipo_de_trabajo','nivel_laboral','nombre_area_aux'],axis=1,inplace=True)
prediccion.head()

   id  sepostulo
0   0   0.087870
1   1   0.088166
2   2   0.011211
3   3   0.083799
4   4   0.000737

In [40]:
prediccion.to_csv("../../Data/fiuba_entrenamiento/gian/predicciones/prediccion62.csv",index=False)

In [41]:
prediccion.sepostulo.mean()

0.47557699691253846