In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.externals import joblib

%matplotlib inline

In [ ]:
plt.rc('figure',dpi=100);

In [ ]:
avisos = pd.read_csv("../../Data/fiuba_entrenamiento/gian/avisosONEHOT.csv")
postulaciones = pd.read_csv("../../Data/fiuba_entrenamiento/gian/postulaciones.csv")
postulantes = pd.read_csv("../../Data/fiuba_entrenamiento/gian/postulantesONEHOT.csv")
postulaciones['sepostulo']=1
postulaciones.drop(['fechapostulacion','dia','mes','semana','diadelasemana','hora'],axis=1,inplace=True)

In [ ]:
vistas = pd.read_csv("../../Data/fiuba_entrenamiento/gian/vistas.csv")
vistas.head()

In [ ]:
vistas.drop(['timestamp','dia','mes','semana','diadelasemana','hora'],axis=1,inplace=True)
vistas['cantidad']=0
vistas=vistas.groupby(['idAviso','idpostulante'],as_index=False).agg({'cantidad':'count'})
vistas=vistas.rename(columns={'idAviso': 'idaviso'})
vistas.head()

In [ ]:
postulaciones2= pd.read_csv("../../Data/fiuba_entrenamiento/gian/no-postulaciones/1.csv")

postulaciones=pd.merge(postulaciones,postulantes,on='idpostulante')
postulaciones2=pd.merge(postulaciones2,postulantes,on='idpostulante')

postulaciones=pd.merge(postulaciones,avisos,on='idaviso')
postulaciones2=pd.merge(postulaciones2,avisos,on='idaviso')

postulaciones2.head()

In [ ]:
postulaciones.head()

In [ ]:
postulaciones=postulaciones.append(postulaciones2, ignore_index=True)
print(len(postulaciones))
postulaciones.drop_duplicates(['idaviso','idpostulante'],keep='first',inplace=True)
print(len(postulaciones))

In [ ]:
postulaciones=pd.merge(postulaciones,vistas,on=['idaviso','idpostulante'],how='left')
postulaciones.sample(20)

In [ ]:
postulaciones.cantidad=postulaciones.cantidad.fillna(0)
postulaciones.sample(20)

In [ ]:
areas=avisos['nombre_area'].value_counts().index
postulaciones['nombre_area']=postulaciones['nombre_area'].replace(areas, range(len(areas)))

In [ ]:
train, test=train_test_split(postulaciones,test_size=0.10)
print("Train: ",len(train),"Test: ",len(test))
features=list(postulaciones.columns)
features.remove('idaviso')
features.remove('idpostulante')
features.remove('sepostulo')
features.remove('titulo')
features.remove('denominacion_empresa')

x_train=train[features]
y_train=train['sepostulo']

x_test=test[features]
y_test=test['sepostulo']
postulaciones=0
postulaciones2=0

In [12]:
import gc
gc.collect()

290

In [14]:
c=DecisionTreeClassifier(min_samples_split=100)
#c = joblib.load("../../Data/fiuba_entrenamiento/gian/modelos/arbol.pkl") 
dt=c.fit(x_train,y_train)

MemoryError:

In [37]:
y_pred=c.predict(x_test)
score=accuracy_score(y_test,y_pred)*100
print(score)

73.05818846156029

In [38]:
joblib.dump(c, "../../Data/fiuba_entrenamiento/gian/modelos/arbolONEHOT.pkl")

['../../Data/fiuba_entrenamiento/gian/modelos/arbol.pkl']

In [39]:
prediccion = pd.read_csv("../../Data/fiuba_entrenamiento/test_final_100k.csv")
print(len(prediccion))
prediccion=pd.merge(prediccion,postulantes,on='idpostulante',how='inner')
print(len(prediccion))
prediccion=pd.merge(prediccion,avisos,on='idaviso',how='inner')
print(len(prediccion))
prediccion=pd.merge(prediccion,vistas,on=['idaviso','idpostulante'],how='left')
prediccion.cantidad=prediccion.cantidad.fillna(0)
prediccion.sample(10)

100000
100000
100000

,id,idaviso,idpostulante,sexo,edad,Doctorado,Master,Otro,Posgrado,Secundario,...,viajar,empresa_importante,capacitacion,remuneracion_pretendida,graduados,estudiantes,conocimientos_especificos,buen_ambiente,discriminacion,cantidad
53335,61562,1112455533,ekNOqa9,MASC,23.0,-,-,-,-,Graduado,...,False,False,False,False,False,False,False,False,False,0.0
8272,54291,1112446392,ZGvkAz,MASC,50.0,-,-,-,-,Graduado,...,False,True,False,False,False,False,False,False,False,0.0
26198,25291,1112334788,kPjwdbJ,FEM,18.0,-,-,-,-,Graduado,...,False,False,True,False,False,False,False,True,False,3.0
95577,95031,1112487047,abM1MZ,FEM,41.0,-,-,-,-,Graduado,...,False,True,False,False,False,False,False,True,False,0.0
44318,51299,1112441384,59vWDZ,FEM,32.0,-,-,-,-,-,...,False,False,False,False,False,False,False,False,False,0.0
60138,8556,1111784905,NPJrzz,MASC,44.0,-,-,-,Graduado,Graduado,...,False,False,True,False,False,False,False,False,False,0.0
54738,73083,1112463294,EzeoKY6,FEM,23.0,-,-,En Curso,-,Graduado,...,False,False,False,True,False,False,False,False,False,1.0
16256,69212,1112461143,6rQROjx,FEM,25.0,-,-,-,-,Graduado,...,False,True,False,False,False,False,False,False,False,6.0
68901,14735,1112096537,YOdv3V,MASC,39.0,-,-,-,-,Graduado,...,False,False,False,False,False,False,False,False,False,0.0
40520,1330,1110564123,8EWNkl,MASC,43.0,-,-,-,-,-,...,False,True,False,False,False,False,False,True,False,0.0

In [41]:
x_final=prediccion[features]
y_final=c.predict(x_final)
y_final

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
prediccion['sepostulo']=y_final

In [43]:
prediccion.head()

,id,idaviso,idpostulante,sexo,edad,Doctorado,Master,Otro,Posgrado,Secundario,...,empresa_importante,capacitacion,remuneracion_pretendida,graduados,estudiantes,conocimientos_especificos,buen_ambiente,discriminacion,cantidad,sepostulo
0,0,739260,6M9ZQR,0,42.0,1,0,0,0,0,...,False,False,False,False,False,False,False,False,0.0,0
1,1,739260,6v1xdL,1,30.0,0,0,1,0,1,...,False,False,False,False,False,False,False,False,0.0,0
2,2,739260,ezRKm9,0,36.0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,0.0,0
3,3,758580,1Q35ej,1,68.0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,0.0,0
4,4,758580,EAN4J6,0,32.0,0,0,0,0,1,...,False,False,False,False,False,False,False,False,0.0,0

In [44]:
prediccion.drop(features,axis=1,inplace=True)
prediccion.drop(['idaviso','idpostulante','titulo','denominacion_empresa'],axis=1,inplace=True)
prediccion.head()

   id  sepostulo
0   0          0
1   1          0
2   2          0
3   3          0
4   4          0

In [45]:
prediccion.to_csv("../../Data/fiuba_entrenamiento/gian/predicciones/prediccion3.csv",index=False)

In [46]:
prediccion.sepostulo.mean()

0.55496