In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.externals import joblib
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb
import gc

%matplotlib inline

In [ ]:
plt.rc('figure',dpi=100);

In [ ]:
avisos = pd.read_csv("../../Data/fiuba_entrenamiento/gian/avisos.csv")
postulaciones = pd.read_csv("../../Data/fiuba_entrenamiento/gian/postulaciones.csv")
postulantes = pd.read_csv("../../Data/fiuba_entrenamiento/gian/postulantes.csv")

postulantes['sexo']=postulantes['sexo'].astype('category')
postulantes['Doctorado']=postulantes['Doctorado'].astype('category')
postulantes['Master']=postulantes['Master'].astype('category')
postulantes['Otro']=postulantes['Otro'].astype('category')
postulantes['Posgrado']=postulantes['Posgrado'].astype('category')
postulantes['Secundario']=postulantes['Secundario'].astype('category')
postulantes['Terciario/Técnico']=postulantes['Terciario/Técnico'].astype('category')
postulantes['Universitario']=postulantes['Universitario'].astype('category')

avisos['nombre_zona']=avisos['nombre_zona'].astype('category')
avisos['tipo_de_trabajo']=avisos['tipo_de_trabajo'].astype('category')
avisos['nivel_laboral']=avisos['nivel_laboral'].astype('category')
avisos['nombre_area']=avisos['nombre_area'].astype('category')
avisos['denominacion_empresa']=avisos['denominacion_empresa'].astype('category')

postulaciones['sepostulo']=1
postulaciones.drop(['fechapostulacion','dia','mes','semana','diadelasemana','hora'],axis=1,inplace=True)

In [ ]:
vistas = pd.read_csv("../../Data/fiuba_entrenamiento/gian/vistas.csv")
vistas.head()

In [ ]:
vistas.drop(['timestamp','dia','mes','semana','diadelasemana','hora'],axis=1,inplace=True)
vistas['cantidad']=0
vistas2=vistas.groupby(['idAviso','idpostulante'],as_index=False).agg({'cantidad':'count'})
vistas2=vistas2.rename(columns={'idAviso': 'idaviso'})
vistas2.head()

In [ ]:
vistas=vistas.groupby(['idpostulante'],as_index=False).agg({'cantidad':'count'});
vistas=vistas.rename(columns={'idAviso': 'idaviso'})
vistas.head()

In [ ]:
vistas2=pd.merge(vistas2,vistas,on='idpostulante',how='left')

In [ ]:
vistas2.head()

In [ ]:
vistas2['cantidad']=vistas2['cantidad_x']/vistas2['cantidad_y']
vistas2.drop(['cantidad_x','cantidad_y'],axis=1,inplace=True)
vistas=vistas2
vistas2.head()

In [ ]:
postulaciones2= pd.read_csv("../../Data/fiuba_entrenamiento/gian/no-postulaciones/7.csv")
postulaciones2=postulaciones2.append(pd.read_csv("../../Data/fiuba_entrenamiento/gian/no-postulaciones/8.csv").sample(len(postulaciones2)//2).reset_index(drop=True))
print(len(postulaciones2))
postulaciones2

In [ ]:
postulaciones.head()

In [ ]:
postulaciones=postulaciones.append(postulaciones2, ignore_index=True)
print(len(postulaciones))
postulaciones2=0
gc.collect()
postulaciones.drop_duplicates(['idaviso','idpostulante'],keep='first',inplace=True)
print(len(postulaciones))

In [ ]:
postulaciones=pd.merge(postulaciones,postulantes,on='idpostulante')
postulaciones=pd.merge(postulaciones,avisos,on='idaviso')
postulaciones=pd.merge(postulaciones,vistas,on=['idaviso','idpostulante'],how='left')
postulaciones.sample(20)

In [ ]:
postulaciones.cantidad=postulaciones.cantidad.fillna(0)
postulaciones.sample(20)

In [ ]:
postulaciones_por_area=postulaciones.copy()
postulaciones_por_area=postulaciones_por_area.groupby(by=['idpostulante','nombre_area'],as_index=False).agg({'sepostulo':'count'})
postulaciones_por_area=postulaciones_por_area.rename(columns={'sepostulo':'postulaciones_misma_area'})
postulaciones_por_area.head()

In [ ]:
postulaciones_por_nivel=postulaciones.copy()
postulaciones_por_nivel=postulaciones_por_nivel.groupby(by=['idpostulante','nivel_laboral'],as_index=False).agg({'sepostulo':'count'})
postulaciones_por_nivel=postulaciones_por_nivel.rename(columns={'sepostulo':'postulaciones_mismo_nivel'})
postulaciones_por_nivel.head()

In [ ]:
postulaciones_por_tipo=postulaciones.copy()
postulaciones_por_tipo=postulaciones_por_tipo.groupby(by=['idpostulante','tipo_de_trabajo'],as_index=False).agg({'sepostulo':'count'})
postulaciones_por_tipo=postulaciones_por_tipo.rename(columns={'sepostulo':'postulaciones_mismo_tipo'})
postulaciones_por_tipo.head()

In [ ]:
postulaciones=pd.merge(postulaciones,postulaciones_por_area,on=['idpostulante','nombre_area'],how='left')
postulaciones=pd.merge(postulaciones,postulaciones_por_tipo,on=['idpostulante','tipo_de_trabajo'],how='left')
postulaciones=pd.merge(postulaciones,postulaciones_por_nivel,on=['idpostulante','nivel_laboral'],how='left')
postulaciones['postulaciones_misma_area']=postulaciones['postulaciones_misma_area'].fillna(0).apply(lambda x: x if(x<=0) else x-1)
postulaciones['postulaciones_mismo_nivel']=postulaciones['postulaciones_mismo_nivel'].fillna(0).apply(lambda x: x if(x<=0) else x-1)
postulaciones['postulaciones_mismo_tipo']=postulaciones['postulaciones_mismo_tipo'].fillna(0).apply(lambda x: x if(x<=0) else x-1)
postulaciones.sample(20)

In [ ]:
train, test=train_test_split(postulaciones,test_size=0.05)
print("Train: ",len(train),"Test: ",len(test))
features=list(postulaciones.columns)
features.remove('idaviso')
features.remove('idpostulante')
features.remove('sepostulo')
features.remove('titulo')

x_train=train[features]
y_train=train['sepostulo']

x_test=test[features]
y_test=test['sepostulo']
postulaciones=0
vistas2=0

In [ ]:
gc.collect()

In [22]:
c=lgb.LGBMClassifier(learning_rate=0.01,objective='binary',num_leaves=6000,max_depth=18,n_estimators=20,colsample_bytree=0.8,n_jobs=-1,random_state=0,silent=False,subsample=0.8,sumsample_freq=0.5)

dt=c.fit(x_train,y_train,eval_set=[(x_test,y_test)],verbose=True,early_stopping_rounds=1)
#c = joblib.load("../../Data/fiuba_entrenamiento/gian/modelos/....pkl")

[1]	valid_0's binary_logloss: 0.686786
Training until validation scores don't improve for 1 rounds.
[2]	valid_0's binary_logloss: 0.679834
[3]	valid_0's binary_logloss: 0.672683
[4]	valid_0's binary_logloss: 0.665696
[5]	valid_0's binary_logloss: 0.660011
[6]	valid_0's binary_logloss: 0.653238
[7]	valid_0's binary_logloss: 0.646919
[8]	valid_0's binary_logloss: 0.640391
[9]	valid_0's binary_logloss: 0.634008
[10]	valid_0's binary_logloss: 0.627774
[11]	valid_0's binary_logloss: 0.622049
[12]	valid_0's binary_logloss: 0.616001
[13]	valid_0's binary_logloss: 0.610595
[14]	valid_0's binary_logloss: 0.604985
[15]	valid_0's binary_logloss: 0.599605
[16]	valid_0's binary_logloss: 0.594368
[17]	valid_0's binary_logloss: 0.588787
[18]	valid_0's binary_logloss: 0.583815
[19]	valid_0's binary_logloss: 0.578947
[20]	valid_0's binary_logloss: 0.574052
Did not meet early stopping. Best iteration is:
[20]	valid_0's binary_logloss: 0.574052

In [23]:
score=c.score(x_test,y_test)*100
print(score)

91.95645957404483

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [24]:
joblib.dump(c, "../../Data/fiuba_entrenamiento/gian/modelos/liviano v5.pkl")

['../../Data/fiuba_entrenamiento/gian/modelos/liviano v5.pkl']

In [25]:
prediccion = pd.read_csv("../../Data/fiuba_entrenamiento/test_final_100k.csv")
print(len(prediccion))
prediccion=pd.merge(prediccion,postulantes,on='idpostulante',how='inner')
print(len(prediccion))
prediccion=pd.merge(prediccion,avisos,on='idaviso',how='inner')
print(len(prediccion))
prediccion=pd.merge(prediccion,vistas,on=['idaviso','idpostulante'],how='left')
prediccion.cantidad=prediccion.cantidad.fillna(0)
prediccion=pd.merge(prediccion,postulaciones_por_area,on=['idpostulante','nombre_area'],how='left')
prediccion=pd.merge(prediccion,postulaciones_por_tipo,on=['idpostulante','tipo_de_trabajo'],how='left')
prediccion=pd.merge(prediccion,postulaciones_por_nivel,on=['idpostulante','nivel_laboral'],how='left')
prediccion['postulaciones_misma_area']=prediccion['postulaciones_misma_area'].fillna(0)
prediccion['postulaciones_mismo_nivel']=prediccion['postulaciones_mismo_nivel'].fillna(0)
prediccion['postulaciones_mismo_tipo']=prediccion['postulaciones_mismo_tipo'].fillna(0)
prediccion.sample(10)

100000
100000
100000

,id,idaviso,idpostulante,sexo,edad,Doctorado,Master,Otro,Posgrado,Secundario,...,remuneracion_pretendida,graduados,estudiantes,conocimientos_especificos,buen_ambiente,discriminacion,cantidad,postulaciones_misma_area,postulaciones_mismo_tipo,postulaciones_mismo_nivel
36961,45365,1112428207,LN8apbq,MASC,28.0,-,-,-,-,Graduado,...,False,False,False,False,False,False,0.000000,3.0,26.0,19.0
85767,35097,1112409905,5LZYvz,MASC,37.0,-,-,-,-,Graduado,...,False,False,False,False,False,False,0.000000,0.0,22.0,15.0
97424,97172,1112498357,YRLaOZ,MASC,36.0,-,-,-,-,Graduado,...,False,False,False,False,False,False,0.000000,0.0,21.0,0.0
18232,74381,1112463706,EzEzpRo,MASC,21.0,-,-,-,-,-,...,True,False,False,False,False,False,0.003247,93.0,413.0,246.0
59498,41931,1112422141,EDAGDN,MASC,38.0,-,-,-,Graduado,-,...,False,False,False,False,False,False,0.021978,1.0,29.0,3.0
62754,10385,1111909936,88ZQYM,FEM,41.0,-,-,-,-,-,...,False,False,False,False,False,False,0.000000,0.0,21.0,6.0
89967,53380,1112444978,NBRB8V,FEM,32.0,-,-,-,-,-,...,False,False,False,False,False,False,0.000000,0.0,18.0,12.0
37748,73143,1112463328,RzPBVB1,MASC,21.0,-,-,-,-,-,...,False,False,False,False,True,False,0.047619,2.0,23.0,17.0
20944,79895,1112464741,X9k4vvv,FEM,35.0,-,Graduado,-,-,Graduado,...,False,False,False,False,False,False,0.032258,2.0,144.0,110.0
60308,73969,1112463522,ZDlLkA1,MASC,37.0,-,-,Graduado,-,Graduado,...,False,False,False,False,False,False,0.341463,3.0,26.0,18.0

In [26]:
x_final=prediccion[features]
y_final=c.predict_proba(x_final)
y_final

array([[0.58380596, 0.41619404],
       [0.54078497, 0.45921503],
       [0.58053161, 0.41946839],
       ...,
       [0.58367055, 0.41632945],
       [0.58507536, 0.41492464],
       [0.57207021, 0.42792979]])

In [27]:
y_final2=[]
print(c.classes_)
print(len(y_final))
for elem in y_final:
    y_final2.append(elem[1])
print(len(y_final2))

[0 1]
100000
100000

In [28]:
prediccion['sepostulo']=y_final2

In [29]:
prediccion.head()

,id,idaviso,idpostulante,sexo,edad,Doctorado,Master,Otro,Posgrado,Secundario,...,graduados,estudiantes,conocimientos_especificos,buen_ambiente,discriminacion,cantidad,postulaciones_misma_area,postulaciones_mismo_tipo,postulaciones_mismo_nivel,sepostulo
0,0,739260,6M9ZQR,FEM,42.0,Graduado,-,-,-,Graduado,...,False,False,False,False,False,0.0,1.0,18.0,0.0,0.416194
1,1,739260,6v1xdL,MASC,30.0,-,-,Graduado,-,-,...,False,False,False,False,False,0.0,6.0,64.0,0.0,0.459215
2,2,739260,ezRKm9,FEM,36.0,-,-,-,-,Graduado,...,False,False,False,False,False,0.0,3.0,18.0,1.0,0.419468
3,3,758580,1Q35ej,MASC,68.0,-,-,-,Graduado,Graduado,...,False,False,False,False,False,0.0,1.0,22.0,2.0,0.419917
4,4,758580,EAN4J6,FEM,32.0,-,-,-,-,-,...,False,False,False,False,False,0.0,1.0,13.0,1.0,0.412383

In [30]:
prediccion.drop(features,axis=1,inplace=True)
prediccion.drop(['idaviso','idpostulante','titulo'],axis=1,inplace=True)
prediccion.head()

   id  sepostulo
0   0   0.416194
1   1   0.459215
2   2   0.419468
3   3   0.419917
4   4   0.412383

In [31]:
prediccion.to_csv("../../Data/fiuba_entrenamiento/gian/predicciones/liviano v5.csv",index=False)

In [32]:
prediccion.sepostulo.mean()

0.4954551892419632